# Generated by Django 6.0 on 2025-12-15 01:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('dep_docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='appointment_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointments',
            name='appointment_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointments',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='dep_docs.departments'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointments',
            name='doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='dep_docs.doctors'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointments',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointments',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='appointments',
            table='appointments',
        ),
    ]
