# Generated by Django 6.0 on 2025-12-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='service-icons')),
                ('title', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=255)),
                ('published', models.BooleanField()),
                ('priority', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'services',
                'ordering': ('-priority',),
            },
        ),
    ]
