# Generated by Django 6.0 on 2025-12-14 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ('-priority',), 'verbose_name': 'Service', 'verbose_name_plural': 'Service(s)'},
        ),
        migrations.RemoveField(
            model_name='services',
            name='short_description',
        ),
    ]
