# Generated by Django 6.0 on 2025-12-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_services_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='short_description',
            field=models.CharField(default='default value', max_length=255),
            preserve_default=False,
        ),
    ]
