# Generated by Django 6.0 on 2025-12-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep_docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='expertise',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='facebook',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doctors-image'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='linkedin',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='short_intro',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='twitter',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
