# Generated by Django 6.0 on 2025-12-21 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurPricings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField()),
                ('priority', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('normal_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'our_pricings',
            },
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField()),
                ('priority', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='pricings.ourpricings')),
            ],
            options={
                'db_table': 'pricing_features',
            },
        ),
    ]
